version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quicklic_dg01
    ports:
      - "8000:8000"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver_plus 0.0.0.0:8000"
    env_file:
      - ./env/.env.dev
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:12.1
    container_name: quicklic_ps01
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.dev

volumes:
  postgres_data:
