version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quicklic_dg01
    ports:
      - "8000:8000"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
